
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'


export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'

export const PUBLISH_BLOG_START = 'PUBLISH_BLOG_START'
export const PUBLISH_BLOG_SUCCESS = 'PUBLISH_BLOG_SUCCESS'
export const PUBLISH_BLOG_FAILED = 'PUBLISH_BLOG_FAILED'

export const FETCH_BLOGS_START = 'FETCH_BLOGS_START'
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS'
export const FETCH_BLOGS_FAILED = 'FETCH_BLOGS_FAILED'

export const FETCH_PARTICULAR_BLOG_START = 'FETCH_PARTICULAR_BLOG_START'
export const FETCH_PARTICULAR_BLOG_SUCCESS = 'FETCH_PARTICULAR_BLOG_SUCCESS'
export const FETCH_PARTICULAR_BLOG_FAILED = 'FETCH_PARTICULAR_BLOG_FAILED'